-- MySQL Script generated by MySQL Workbench
-- Fri Jul 17 15:57:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema medicode
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rol` ;

CREATE TABLE IF NOT EXISTS `rol` (
  `id_rol` TINYINT NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX (`name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `status` ;

CREATE TABLE IF NOT EXISTS `status` (
  `id_status` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_status`),
  UNIQUE INDEX (`type` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `specialty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `specialty` ;

CREATE TABLE IF NOT EXISTS `specialty` (
  `id_specialty` TINYINT NULL DEFAULT NULL AUTO_INCREMENT,
  `specialty_name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `is_active` TINYINT NULL DEFAULT TRUE,
  PRIMARY KEY (`id_specialty`));


-- -----------------------------------------------------
-- Table `prescription_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prescription_item` ;

CREATE TABLE IF NOT EXISTS `prescription_item` (
  `id_item` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id_item`));


-- -----------------------------------------------------
-- Table `consultation_diagnoses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consultation_diagnoses` ;

CREATE TABLE IF NOT EXISTS `consultation_diagnoses` (
  `id_diagnoses` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `cie10_code` VARCHAR(20) NULL DEFAULT NULL,
  `diagnosis_name` VARCHAR(255) NOT NULL,
  `diagnoses_type` ENUM('presumptive', 'definitive') NOT NULL,
  `clinical_notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_diagnoses`));


-- -----------------------------------------------------
-- Table `prescriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prescriptions` ;

CREATE TABLE IF NOT EXISTS `prescriptions` (
  `id_prescription` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `general_instruction` TEXT NULL DEFAULT NULL,
  `requires_follow_up` TINYINT NULL DEFAULT FALSE,
  `follow_up_timeframe` ENUM('7', '14', '28') NULL DEFAULT NULL,
  `prescriptionscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_prescription`));


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id_user` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `rol` TINYINT NOT NULL,
  `is_active` TINYINT NULL DEFAULT TRUE,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX (`mail` ASC) VISIBLE,
  CONSTRAINT `fk_user_rol_user_rol`
    FOREIGN KEY (`rol`)
    REFERENCES `rol` (`id_rol`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doctor` ;

CREATE TABLE IF NOT EXISTS `doctor` (
  `id_doctor` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `professional_id` VARCHAR(50) NULL DEFAULT NULL,
  `specialty` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_doctor`),
  CONSTRAINT `fk_user_id_user_doctor`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_specialty_id_specialty_doctor`
    FOREIGN KEY (`specialty`)
    REFERENCES `specialty` (`id_specialty`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `user_hours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_hours` ;

CREATE TABLE IF NOT EXISTS `user_hours` (
  `id_hours` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  `day` TINYINT NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `is_active` TINYINT NULL DEFAULT TRUE,
  PRIMARY KEY (`id_hours`),
  CONSTRAINT `fk_user_id_user_user_hours`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `patients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patients` ;

CREATE TABLE IF NOT EXISTS `patients` (
  `id_patient` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `date_of_birth` DATE NOT NULL,
  `gender` CHAR(1) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `NSS` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_patient`),
  UNIQUE INDEX (`NSS` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `patient_chronic_conditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patient_chronic_conditions` ;

CREATE TABLE IF NOT EXISTS `patient_chronic_conditions` (
  `id_condition` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `patient_id` INT NOT NULL,
  `condition_name` VARCHAR(100) NOT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_condition`),
  CONSTRAINT `fk_condition_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `patients` (`id_patient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appointment` ;

CREATE TABLE IF NOT EXISTS `appointment` (
  `id_appointment` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `patient_id` INT NOT NULL,
  `doctor_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id_appointment`),
  CONSTRAINT `fk_patients_id_patient_appointment`
    FOREIGN KEY (`patient_id`)
    REFERENCES `patients` (`id_patient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_doctor_id_doctor_appointment`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `doctor` (`id_doctor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_appointment_status_status`
    FOREIGN KEY (`status`)
    REFERENCES `status` (`id_status`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `initial_assessments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `initial_assessments` ;

CREATE TABLE IF NOT EXISTS `initial_assessments` (
  `id_assessment` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `appointment_id` INT NOT NULL,
  `weight` DECIMAL(5,2) NULL DEFAULT NULL,
  `height` INT NULL DEFAULT NULL,
  `temperature` DECIMAL(4,2) NULL DEFAULT NULL,
  `systolic_bp` INT NULL DEFAULT NULL,
  `diastolic_bp` INT NULL DEFAULT NULL,
  `consciousness_state` TINYINT NULL DEFAULT NULL,
  `has_fever` TINYINT NULL DEFAULT FALSE,
  `has_pain` TINYINT NULL DEFAULT FALSE,
  `has_cough` TINYINT NULL DEFAULT FALSE,
  `has_nausea` TINYINT NULL DEFAULT FALSE,
  `has_chills` TINYINT NULL DEFAULT FALSE,
  `nutritional_state` TINYINT NULL DEFAULT NULL,
  `mobility_state` TINYINT NULL DEFAULT NULL,
  `assessment_note` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_assessment`),
  CONSTRAINT `fk_assessment_appointment`
    FOREIGN KEY (`appointment_id`)
    REFERENCES `appointment` (`id_appointment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `prescription_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prescription_details` ;

CREATE TABLE IF NOT EXISTS `prescription_details` (
  `id_detail` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `prescription_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `dose` ENUM('days', 'weeks', 'month') NULL,
  `route_of_administration` ENUM('Oral', 'Sublingual', 'Rectal', 'Intravenous', 'Intramuscular', 'Subcutaneous', 'Intradermal', 'Topical', 'Inhalation', 'Ophthalmic', 'Vaginal') NULL,
  PRIMARY KEY (`id_detail`),
  CONSTRAINT `fk_prescription_details_prescription`
    FOREIGN KEY (`prescription_id`)
    REFERENCES `prescriptions` (`id_prescription`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prescriptions_prescription_item_prescription_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `prescription_item` (`id_item`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reports` ;

CREATE TABLE IF NOT EXISTS `reports` (
  `id_reports` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `appointment_id` INT NOT NULL,
  `prescriptions_id` INT NULL DEFAULT NULL,
  `diagnoses_id` INT NULL DEFAULT NULL,
  `assessment_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_reports`),
  CONSTRAINT `fk_appointment_id_appointment_reports`
    FOREIGN KEY (`appointment_id`)
    REFERENCES `appointment` (`id_appointment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reports_prescriptions_id_prescriptions`
    FOREIGN KEY (`prescriptions_id`)
    REFERENCES `prescriptions` (`id_prescription`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reports_diagnoses_id_consultation_diagnoses`
    FOREIGN KEY (`diagnoses_id`)
    REFERENCES `consultation_diagnoses` (`id_diagnoses`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reports_assessment_id_initial_assessments`
    FOREIGN KEY (`assessment_id`)
    REFERENCES `initial_assessments` (`id_assessment`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
